spring:
    application:
        name: app
    datasource:
        url: jdbc:mysql://localhost:3306/nagarjan?createDatabaseIfNotExist=true
        username: root
        password: asdfghjkl
    jwt:
        secret: 8qtugbynq87dtyn278ynw87oeyfnm9pf8yndmq9pmq9fpoinmyg2ujsavxuoasbkxgou3
    allowed:
        origin: http://localhost:4200
    jpa:
        show-sql: true

otpauth:
    validforminutes: 5